# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  desc "Prepares the project for a new release (bumps build and version numbers)."
  lane :prepare_release do |options|
    ensure_git_status_clean
    ensure_git_branch(branch: '^release/(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$')
    version_number = git_branch.partition('/').last
    build_number = increment_build_number
    git_commit(path: ".", message: "Bump build number to #{build_number}")
    version_number = increment_version_number(version_number: version_number)
    commit_version_bump(message: "Bump version number to #{version_number}", xcodeproj: "GitHubContributions.xcodeproj")
  end
end
